<?php declare(strict_types=1);

return [
	'PHPDD18-WS-01' => [
		'name'             => 'Workshop Ticket Slot A1',
		'description'      => 'Half-day workshop from 09:00am to 1:30pm on September 21st 2018',
		'price'            => 14900,
		'seats'            => 25,
		'maxSeatsPerOrder' => 3,
		'type'             => \PHPUGDD\PHPDD\Website\Tickets\Application\Constants\TicketTypes::FULLDAY_WORKSHOP,
		'validFrom'        => '2018-05-01 00:00:00',
		'validTo'          => '2018-09-15 23:59:59',
		'image'            => '/assets/images/tickets/workshop.png',
	],
	'PHPDD18-WS-02' => [
		'name'             => 'Workshop Ticket Slot A2',
		'description'      => 'Half-day workshop from 02:30pm to 07:00pm on September 21st 2018',
		'price'            => 14900,
		'seats'            => 25,
		'maxSeatsPerOrder' => 3,
		'type'             => \PHPUGDD\PHPDD\Website\Tickets\Application\Constants\TicketTypes::FULLDAY_WORKSHOP,
		'validFrom'        => '2018-01-01 00:00:00',
		'validTo'          => '2018-09-15 23:59:59',
		'image'            => '/assets/images/tickets/workshop.png',
	],
	'PHPDD18-WS-03' => [
		'name'             => 'Workshop Ticket Slot B1',
		'description'      => 'Half-day workshop from 09:00am to 01:30pm on September 21st 2018',
		'price'            => 14900,
		'seats'            => 25,
		'maxSeatsPerOrder' => 3,
		'type'             => \PHPUGDD\PHPDD\Website\Tickets\Application\Constants\TicketTypes::FULLDAY_WORKSHOP_B,
		'validFrom'        => '2018-01-01 00:00:00',
		'validTo'          => '2018-09-15 23:59:59',
		'image'            => '/assets/images/tickets/workshop.png',
	],
	'PHPDD18-WS-04' => [
		'name'             => 'Workshop Ticket Slot B2',
		'description'      => 'Half-day workshop from 02:30pm to 07:00pm on September 21st 2018',
		'price'            => 14900,
		'seats'            => 2,
		'maxSeatsPerOrder' => 3,
		'type'             => \PHPUGDD\PHPDD\Website\Tickets\Application\Constants\TicketTypes::FULLDAY_WORKSHOP_B,
		'validFrom'        => '2018-01-01 00:00:00',
		'validTo'          => '2018-09-15 23:59:59',
		'image'            => '/assets/images/tickets/workshop.png',
	],
	'PHPDD18-WS-05' => [
		'name'             => 'Workshop Ticket Slot C1',
		'description'      => 'Full-day workshop from 09:00am to 07:00pm on September 21st 2018',
		'price'            => 24900,
		'seats'            => 3,
		'maxSeatsPerOrder' => 3,
		'type'             => \PHPUGDD\PHPDD\Website\Tickets\Application\Constants\TicketTypes::HALFDAY_WORKSHOP_A,
		'validFrom'        => '2018-01-01 00:00:00',
		'validTo'          => '2018-09-15 23:59:59',
		'image'            => '/assets/images/tickets/workshop.png',
	],
	'PHPDD18-ES-01' => [
		'name'             => 'Early Bird Conference Ticket',
		'description'      => 'Grants access to all conference session on September 22nd 2018.',
		'price'            => 6900,
		'seats'            => 50,
		'maxSeatsPerOrder' => 5,
		'type'             => \PHPUGDD\PHPDD\Website\Tickets\Application\Constants\TicketTypes::CONFERENCE,
		'validFrom'        => '2018-01-01 00:00:00',
		'validTo'          => '2018-05-31 23:59:59',
		'image'            => '/assets/images/tickets/early-bird.png',
	],
	'PHPDD18-CT-01' => [
		'name'             => 'Conference Ticket',
		'description'      => 'Grants access to all conference session on September 22nd 2018.',
		'price'            => 9900,
		'seats'            => 400,
		'maxSeatsPerOrder' => 10,
		'type'             => \PHPUGDD\PHPDD\Website\Tickets\Application\Constants\TicketTypes::CONFERENCE,
		'validFrom'        => '2018-06-01 00:00:00',
		'validTo'          => '2018-09-15 23:59:59',
		'image'            => '/assets/images/tickets/conference.png',
	],
];
