version: '3.1'

services:
  redis:
    image: redis:4
    container_name: phpdd18-redis
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379

  readis:
    image: hollodotme/readis:2
    container_name: phpdd18-readis
    restart: always
    volumes:
      - ./data/readis:/code/config:ro
    ports:
      - 8079:80
    depends_on:
      - redis

  mysql:
    image: mysql/mysql-server:5.5
    container_name: phpdd18-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=phpdd18
      - MYSQL_USER=phpdd18
      - MYSQL_PASSWORD=phpdd18
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306
