version: '3.1'

services:
  redis:
    image: redis:4
    container_name: phpdd18-redis
    restart: always
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379

  readis:
    image: hollodotme/readis:2
    container_name: phpdd18-readis
    restart: always
    volumes:
      - ./data/readis:/code/config:ro
    ports:
      - 8079:80
    depends_on:
      - redis

  mysql:
    image: mysql/mysql-server:5.5
    container_name: phpdd18-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=phpdd18
      - MYSQL_USER=phpdd18
      - MYSQL_PASSWORD=phpdd18
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  php-fpm:
    image: hollodotme/phpdd18-php-fpm
    container_name: phpdd18-php
    restart: always
    volumes:
      - ./:/repo
    ports:
      - 9000:9000

  nginx:
    image: nginx
    container_name: phpdd18-nginx
    restart: always
    volumes:
      - ./data/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./data/nginx/server.crt:/etc/ssl/tickets.phpdd.devel.crt
      - ./data/nginx/server.key:/etc/ssl/tickets.phpdd.devel.key
      - ./:/repo
    ports:
      - 80:80
      - 443:443
    depends_on:
      - php-fpm
