<?php declare(strict_types=1);

return [
	'WORKSHOP - PRAGMATIC TDD'                      => [
		'description'      => 'Trainer: Luka Mužinić<br>Full-day workshop from 09:00am to 7:00pm on September 21st 2018',
		'price'            => 24900,
		'seats'            => 25,
		'maxSeatsPerOrder' => 3,
		'type'             => \PHPUGDD\PHPDD\Website\Tickets\Application\Constants\TicketTypes::WORKSHOP_SLOT_A,
		'validFrom'        => '2018-05-01 00:00:00',
		'validTo'          => '2018-09-15 23:59:59',
		'image'            => '/assets/images/speakers/luka-muzinic.jpg',
	],
	'WORKSHOP - PRGAMATIC EVENT SOURCING'           => [
		'description'      => 'Trainers: Arne Blankerts & Sebastian Heuer<br>Full-day workshop from 09:00am to 7:00pm on September 21st 2018',
		'price'            => 24900,
		'seats'            => 25,
		'maxSeatsPerOrder' => 3,
		'type'             => \PHPUGDD\PHPDD\Website\Tickets\Application\Constants\TicketTypes::WORKSHOP_SLOT_B,
		'validFrom'        => '2018-01-01 00:00:00',
		'validTo'          => '2018-09-15 23:59:59',
		'image'            => '/assets/images/speakers/arne-sebastian.png',
	],
	'WORKSHOP - HACK THIS WORKSHOP!'                => [
		'description'      => 'Trainer: Christopher Riley<br>Half-day workshop from 09:00am to 01:30pm on September 21st 2018',
		'price'            => 14900,
		'seats'            => 25,
		'maxSeatsPerOrder' => 3,
		'type'             => \PHPUGDD\PHPDD\Website\Tickets\Application\Constants\TicketTypes::WORKSHOP_SLOT_C,
		'validFrom'        => '2018-01-01 00:00:00',
		'validTo'          => '2018-09-15 23:59:59',
		'image'            => '/assets/images/speakers/christopher-riley.jpg',
	],
	"WORKSHOP - PENTESTING DO's & DONT's"           => [
		'description'      => 'Trainer: Clinton Ingrams<br>Half-day workshop from 02:30pm to 07:00pm on September 21st 2018',
		'price'            => 14900,
		'seats'            => 25,
		'maxSeatsPerOrder' => 3,
		'type'             => \PHPUGDD\PHPDD\Website\Tickets\Application\Constants\TicketTypes::WORKSHOP_SLOT_C,
		'validFrom'        => '2018-01-01 00:00:00',
		'validTo'          => '2018-09-15 23:59:59',
		'image'            => '/assets/images/speakers/clinton-ingrams.jpg',
	],
	'WORKSHOP - EVENT STORMING FOR FUN AND PROFIT!' => [
		'description'      => 'Trainer: Jeroen van der Gulik<br>Half-day workshop from 09:00am to 01:30pm on September 21st 2018',
		'price'            => 14900,
		'seats'            => 25,
		'maxSeatsPerOrder' => 3,
		'type'             => \PHPUGDD\PHPDD\Website\Tickets\Application\Constants\TicketTypes::WORKSHOP_SLOT_D,
		'validFrom'        => '2018-01-01 00:00:00',
		'validTo'          => '2018-09-15 23:59:59',
		'image'            => '/assets/images/speakers/jeroen-van-der-gulik.jpg',
	],
	'WORKSHOP - TBA'                                => [
		'description'      => 'Trainer: TBA<br>Half-day workshop from 02:30pm to 07:00pm on September 21st 2018',
		'price'            => 14900,
		'seats'            => 25,
		'maxSeatsPerOrder' => 3,
		'type'             => \PHPUGDD\PHPDD\Website\Tickets\Application\Constants\TicketTypes::WORKSHOP_SLOT_D,
		'validFrom'        => '2018-06-01 00:00:00',
		'validTo'          => '2018-09-15 23:59:59',
		'image'            => '/assets/images/tickets/workshop.png',
	],
	'Early Bird Conference Ticket'                  => [
		'description'      => 'Grants access to all conference activity on September 22, 2018.',
		'price'            => 7900,
		'seats'            => 50,
		'maxSeatsPerOrder' => 5,
		'type'             => \PHPUGDD\PHPDD\Website\Tickets\Application\Constants\TicketTypes::CONFERENCE,
		'validFrom'        => '2018-06-01 00:00:00',
		'validTo'          => '2018-09-15 23:59:59',
		'image'            => '/assets/images/tickets/early-bird.png',
	],
	'Conference Ticket'                             => [
		'description'      => 'Grants access to all conference activity on September 22, 2018.',
		'price'            => 11900,
		'seats'            => 400,
		'maxSeatsPerOrder' => 10,
		'type'             => \PHPUGDD\PHPDD\Website\Tickets\Application\Constants\TicketTypes::CONFERENCE,
		'validFrom'        => '2018-06-01 00:00:00',
		'validTo'          => '2018-09-15 23:59:59',
		'image'            => '/assets/images/tickets/conference.png',
	],
];
